Martin
Glimakra-Webbutvecklare-2020/restaurang-menyer pull request #2
Opened 2020-09-21 17:26 UTC by LarssonGitHub

Hej Henry, här är min meny som du beställde! 👍 

Hälsningar Martin

2020-09-23 18:56 UTC, frozenbanana requested changes
- The declaration with  `#forratter, #huvudratter, #efterratter, footer, header` to a class and apply it on each of the sections, footer, and header.
- Remove empty lines inside declarations.

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/index.html
> +    <header id="Header">
If one only is using one `<header>` then `id="Header"`  is redundant. Consider removing `id="Header"` and just select on `header`.

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/index.html
> +                <p class="pris">57kr (£80)</p>
Good use of class here. Good job!

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/index.html
> +            <div class="item">
Good use of class here. Good job!

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/index.html
> +        <section id="huvudratter">
using id here makes sense since you will have 3 sections but they are all unique. Good job!

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/stylesheet.css
> +/*Alla heading barn barn av item*/
blabla > h3 means direct children of blabla

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/stylesheet.css
> +}
Empty lines without purpose are a sin! Use one empty line per declaration. And no empty lines inside declarations.

2020-09-23 18:56 UTC, frozenbanana commented on menyer/kackerlackan/stylesheet.css
> +#forratter, #huvudratter, #efterratter, footer, header {
Important: if have many selectors stacked like this ask yourself if you should perhaps change the selector to something they have all in common. If there is nothing unique about #foratt, #huvudratt,.. etc then don't use it. 

I would change this to a class and then apply it where it is appropriate.

2020-09-24 12:30 UTC, closed without merging

2020-09-24 12:30 UTC, LarssonGitHub commented
skickar en ny med fixad css